services:
  db:
    image: postgres:15-alpine # 'alpine' is a smaller, lighter image
    container_name: rapor_db
    restart: no # Or "no" if you don't want auto-start
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rapor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: rapor@mail.com
      PGADMIN_DEFAULT_PASSWORD: rapor
    ports:
      - "5454:80"

volumes:
  postgres_data:
